# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - id: mineunit
        uses: mt-mods/mineunit-actions@master
      - if: failure() && ! steps.mineunit.outputs.busted-missing-spec
        uses: peter-evans/commit-comment@v1.3.2
        with:
          body: |
            Mineunit failed regression tests, complete test log produced by `busted` follows:
            ```
            ${{ steps.mineunit.outputs.busted-stdout }}
            ```
      - if: failure() && steps.mineunit.outputs.busted-missing-spec
        uses: peter-evans/commit-comment@v1.3.2
        with:
          body: |
            Busted failed, log follows:
            ```
            ${{ steps.mineunit.outputs.busted-stdout }}
            ```
            It seems that your project is missing spec files, you should add spec files inside spec directory.
            If you already have spec directory with `*_spec.lua` files then probelm is probably `working-directory` settings.
            `working-directory` should point to directory where `spec` directory is located. Example when you have `/src/mystuff/spec` directory:
            ```
            - uses: mt-mods/mineunit-actions@master
              with:
                working-directory: ./src/mystuff
            ```
