# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - id: mineunit
        uses: mt-mods/mineunit-actions@badger
      - if: success() && github.event_name == 'pull_request'
        uses: KeisukeYamashita/create-comment@v1
        with:
          check-only-first-line: true
          comment: |
            Detailed test coverage report:
            ```
            File                             Hits Missed Coverage
            -----------------------------------------------------
            ${{ steps.mineunit.outputs.mineunit-report }}
            ```
            Mineunit test runner log:
            ```
            ${{ steps.mineunit.outputs.mineunit-stdout }}
            ```
      - if: failure() && ! steps.mineunit.outputs.mineunit-spec-missing
        uses: peter-evans/commit-comment@v1.3.2
        with:
          body: |
            Mineunit failed regression tests, complete test log produced by `busted` follows:
            ```
            ${{ steps.mineunit.outputs.mineunit-stdout }}
            ```
      - if: failure() && steps.mineunit.outputs.mineunit-spec-missing
        uses: peter-evans/commit-comment@v1.3.2
        with:
          body: |
            Busted failed, log follows:
            ```
            ${{ steps.mineunit.outputs.mineunit-stdout }}
            ```
            ${{ steps.mineunit.outputs.help-busted-spec-missing }}
